import Head from 'next/head'
import Layout from '../../components/admincomponent/utils/layout'
import Dashboard from '../../components/admincomponent/dashboard/dashboard'
export default function Home() {
  return (
    <>
      <Head>
        <title>Boking Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard />
      </Layout>
    </> 
  )
}
